[project]
name = "py-read-multi-figure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.0",
    "ipywidgets>=8.0.0",
    "ipykernel>=6.29.5",
    "pillow>=11.2.1",
    "h5py>=3.14.0",
    "ipyfilechooser>=0.6.0",
    "matplotlib>=3.10.3",
    "ipympl>=0.9.7",
    "simpleeval>=1.0.3",
    "scipy>=1.16.0",
]



[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
